--CREATE TYPE nationality_enum AS ENUM ('UK', 'CN', 'JP', 'US', 'KR', 'FR', 'DE', 'NL', 'OTHER');
--
--CREATE TABLE users (
--  id SERIAL PRIMARY KEY,
--  username VARCHAR(255),
--  description TEXT,
--  nationality nationality_enum,
--  login_type VARCHAR(50),
--  email VARCHAR(255),
--  web_url VARCHAR(255),
--  instagram_id VARCHAR(255),
--  deleted BOOLEAN
--);
