name: Chat Service CICD

on:
  pull_request:
    branches: ["dev"]
    paths:
      - 'chat-service/**'

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Create application.yml
        run: |
          mkdir -p chat-service/src/main/resources
          touch chat-service/src/main/resources/application.yml
          echo "${{ secrets.CHAT_APPLICATION }}" > chat-service/src/main/resources/application.yml
          cat chat-service/src/main/resources/application.yml

      - name: Build Chat Service
        run: |
          ./gradlew :chat-service:build 

