name: Gateway Service CICD

on:
  pull_request:
    branches: ["dev"]
    paths:
      - 'gateway-service/**'

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Create application.yml
        run: |
          mkdir -p gateway-service/src/main/resources
          touch gateway-service/src/main/resources/application.yml
          echo "${{ secrets.GATEWAY_APPLICATION }}" > gateway-service/src/main/resources/application.yml
          cat gateway-service/src/main/resources/application.yml
      - name: Build Gateway Service
        run: |
          ./gradlew :gateway-service:build